Update to the class RainWater
We do not what java.lang.NoSuchMethodError: net.minecraft.block.Block.isBlockNormalCube() if the mod is running on the server.