Update to the class RainWater in the readme.asciidoc file
We do not what a java.lang.NoSuchMethodError: net.minecraft.block.Block.isBlockNormalCube() if the mod is running on the server.